import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/tailwind.css";
import { MyThemeProvider } from "@ssms/utils/providers/MyThemeProvider";
import { MyQueryProvider } from "@ssms/utils/providers/MyQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export type LayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <MyThemeProvider>
          <MyQueryProvider>{children}</MyQueryProvider>
        </MyThemeProvider>
      </body>
    </html>
  );
}
